# Generated by Django 2.0.2 on 2018-02-14 19:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='latent_vector',
            field=jsonfield.fields.JSONField(default=None),
        ),
    ]
